### PR TITLE
Make version number on home page clickable and point to Changelog

### LINKED ISSUE #87: VERSION NUMBER: Open browser to CHANGELOG on tap of version number.
## Description

After #86 add the version to just before the logo, after the status bar.

If the version is tapped then display in a browser URL https://github.com/gjwgit/rattleng/blob/dev/CHANGELOG.md

### PR DESCRIPTION
**Pull request by Lutra-Fs**
# Pull Request Details

## What issue does this PR address

- This PR makes the version number on the home page clickable and points to the Changelog.

- Link to associated issue: #87

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted:
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [x] Linux
  - [ ] MacOS
  - [x] Windows
- [x] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [x] Merge dev into the branch
- [x] Resolve any conflicts
- [x] Add one line summary into CHANGELOG.md
- [x] Bump appropriate version number in pubspec.yaml
- [x] Push to git repository and review
- [x] Merge PR into dev (gjwgit)

### CODE REVIEW

**Review by gjwgit — COMMENTED** [review]
Thanks for the update to home.dart.

Do we need to fvm files in the repo?

**Comment by Lutra-Fs** [comment]
> Thanks for the update to home.dart.
> 
> Do we need to fvm files in the repo?

Accidentally included these files sorry😔

**Review by gjwgit — APPROVED** [review]
Test on Linux.

**Comment by gjwgit** [comment]
Thanks for the update.

**Pull request merged**
