### PR TITLE
Add completer to ensure rStart is passed after pty init

### LINKED ISSUE #264: [WINDOWS] On startup from the zip distrubtion main.R is not run
## Description

For the zip distribution of the rattlng package for Windows, when running the rattle.exe on Windows, after R starts up in the CONSOLE it does not run the main.R script. On Linux and MacOS the main.R script is run on startup.

This task is to investigate why main.R is not run on starting up rattle.exe on Windows.

### PR DESCRIPTION
**Pull request by Lutra-Fs**
# Pull Request Details

## What issue does this PR address

- [A one line description of this PR]

- Link to associated issue: #264 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [x] Tested on device:
  - [x] Linux
  - [ ] MacOS
  - [x] Windows
- [x] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

**Comment by Lutra-Fs** [comment]
I hope that the code will not affect other platforms. Please do extra testing if okay.

**Review by gjwgit — APPROVED** [review]

**Comment by gjwgit** [comment]
This update did not seem to fix the problem for me on my Windows test machine. Reverting the PR

**Comment by Lutra-Fs** [comment]
> This update did not seem to fix the problem for me on my Windows test machine. Reverting the PR

What do you observed? Is that the restart passed to the PTY before the PTY initialized? If possible pls debug print the pty input and attached in the issue comment. Or are you on release build?

**Comment by Lutra-Fs** [comment]
I’m currently at the university and was wondering if we could squeeze in a quick meeting around 2:30 p.m. to go over the issue on your Windows env. No worries if that doesn’t work for you though! @gjwgit

**Comment by Lutra-Fs** [comment]
Have recorded a video. But due to limited bandwidth in uni I am unable to upload it now

**Comment by gjwgit** [comment]
On startup I see the R initial and waiting for code but no code.

**Pull request merged**
