### PR TITLE
Yyx/327 test sherlock

### PR DESCRIPTION
**Pull request by yixiangyin**
# Pull Request Details

## What issue does this PR address

- test sherlock.txt on wordcloud

- Link to associated issue: #327 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [x] Tested on device:
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

**Comment by gjwgit** [comment]
Needs a screenshot of the test succeeding.

**Comment by yixiangyin** [comment]
> Needs a screenshot of the test succeeding.

Hi @gjwgit , I can't seem to finish the test on my pc. Some (random) tests hangs forever as the app hangs sometimes. I had to restart all the tests again :(.
Can you test it for me?
Screenshot 2024-09-23 at 20 39 15

**Review by gjwgit — COMMENTED** [review]
I am getting a test fail after updating to the latest dev. Could you have a quick look please @yixiangyin. Thanks

**Comment by yixiangyin** [comment]
> I am getting a test fail after updating to the latest dev. Could you have a quick look please @yixiangyin. Thanks

Thanks for running @gjwgit .Which test failed?

**Comment by gjwgit** [comment]
image

**Comment by gjwgit** [comment]
image

**Comment by gjwgit** [comment]
Tests now passing

image

**Pull request merged**
