### PR TITLE
Refactor selectFile function to include a default file name parameter

### LINKED ISSUE #395: IMAGE PAGE: SAVE needs good default filename but fails on Ubuntu
20240909 Title updated - focus is becoming the failure of file_picker on Ubuntu, both with inconsistent provision of default filename, missing filter, and exception when [zenity](https://gitlab.gnome.org/GNOME/zenity) is not installed. It assumes either zenity, kdialog, qarma is externally installed. Not the case for Mint (okay for Ubuntu).

+ https://github.com/miguelpruivo/flutter_file_picker/issues/1270
+ https://github.com/miguelpruivo/flutter_file_picker/issues/956

Perhaps fork file_picker and find a solution?

## Description

The image save/export functionality should provide a default filename in the filechooser popup as we see below. Currently Name is empty. It should be the same as the filename in the temp folder (e.g., `model_random_forest_varimp.svg`). The user can then choose to use this name or to change the name and then tap OK.

Also, instead of Custom Files it should be SVG files down the bottom right.

Image

### PR DESCRIPTION
**Pull request by Lutra-Fs**
# Pull Request Details

## What issue does this PR address

- extract the current file name used in temp as the default file name for file picker

- Link to associated issue: #395

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [ ] MacOS
  - [x] Windows
- [ ] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

**Review by gjwgit — COMMENTED** [review]
On Linux I do not see a default filename provided when I tap the SAVE button. Does it work on Windows?

image

**Comment by Lutra-Fs** [comment]
> On Linux I do not see a default filename provided when I tap the SAVE button
> 
> image

I can provide a screenshot.

**Comment by Lutra-Fs** [comment]
image

**Comment by Lutra-Fs** [comment]
image
test on Linux. Zenity is the default file manager `file-picker` trying to use and it seems without your issue.

**Comment by Lutra-Fs** [comment]
See https://github.com/miguelpruivo/flutter_file_picker/issues/1451 We also may need to add zenity as an optional dependency to provide save function

**Comment by gjwgit** [comment]
When I click SAVE in the SCRIPT tab the default filename is listed there. May need to check what the difference is.
image

**Comment by gjwgit** [comment]
They look pretty much identical to me: `lib/utils/select_file.dart` and `lib/tabs/script/save_button.dart`:

```
  String? result = await FilePicker.platform.saveFile(
    dialogTitle: 'Save SVG image to a .svg file',
    fileName: defaultFileName,
    type: FileType.custom,
    allowedExtensions: ['svg'],
  );
```

and 

```
    String? outputPath = await FilePicker.platform.saveFile(
      dialogTitle: 'Choose a file to save',
      fileName: 'script.R',
      type: FileType.custom,
      allowedExtensions: ['R'],
    );
```

That's odd that the first does not work but the second does. This is on Ubuntu 24.04 running Gnome.

**Review by Lutra-Fs — COMMENTED** [review]
It might be better to refactor the one in `save_button` with `select_file` or take out `select_file` and put the content in `image_page`.

**Comment by gjwgit** [comment]
Tried a few alternatives. None worked yet. Tested on Lab Linux:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/linux/file_picker_linux.dart:127)
<asynchronous suspension>
#2      FilePickerLinux.saveFile (package:file_picker/src/linux/file_picker_linux.dart:91)
<asynchronous suspension>
#3      selectFile (package:rattle/utils/select_file.dart:36)
<asynchronous suspension>
#4      ImagePage.build.<anonymous closure>.<anonymous closure> (package:rattle/widgets/image_page.dart:165)
<asynchronous suspension>


** (rattle:2109544): WARNING **: 20:26:43.615: Attempted to set message handler on an FlBinaryMessenger without an engine

** (rattle:2109544): WARNING **: 20:26:43.615: Attempted to set message handler on an FlBinaryMessenger without an engine
```

**Comment by gjwgit** [comment]
We may need to revert to simply asking for a filename in a text field popup until this issue is resolved, perhaps upstream if that's where the problem is? https://github.com/miguelpruivo/flutter_file_picker/issues/1451

**Pull request merged**
