### PR TITLE
Supports selecting file extensions, and adds export to PDF and PNG

### PR DESCRIPTION
**Pull request by Lutra-Fs**
# Pull Request Details

## What issue does this PR address

- Add native functionality to convert SVG to PDF and PNG in app.

- Link to associated issue: #198

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [x] Tested on device:
  - [ ] Linux
  - [ ] MacOS
  - [x] Windows
- [x] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

**Comment by Lutra-Fs** [comment]
Hey! I tried running `make qtest` on my Windows machine but ran into some environment issues. I wanted to get back to this project, but I've been swamped with assignments between mid-semester break and the end of teaching period. Haven't had a chance to look at it at all during that time. Finally now that classes are over, I can pick it up again!

**Comment by Lutra-Fs** [comment]
7ce9c69c9040a4ee93ac942ce5b5198cf6f0a254 introduce pipe uses `date` command, which I get this error:
cmd:
```
E:\rattleng>date +%Y%m%d%H%M%S
The system cannot accept the date entered.
Enter the new date: (dd-mm-yy) 
```

pwsh:
```
date +%Y%m%d%H%M%S
Get-Date: Cannot bind parameter 'Date'. Cannot convert value "+%Y%m%d%H%M%S" to type "System.DateTime". Error: "String '+%Y%m%d%H%M%S' was not recognized as a valid DateTime."
```

make:
```
✦ ❯ make qtest.tmp
process_begin: CreateProcess(NULL, date +%Y%m%d%H%M%S, ...) failed.
support/flutter.mk:307: pipe: Bad file descriptor
```

**Comment by Lutra-Fs** [comment]
Also I think it would be better to turn https://github.com/gjwgit/rattleng/blob/dev/lib/main.dart#L66 `alwaysOnTop` off to avoid the annoying pop up for integration test. I have read the comment but still don't get the idea why we force the app on top of the beginning.

**Comment by Lutra-Fs** [comment]
when running qtest I found https://github.com/gjwgit/rattleng/issues/359 appears again.

**Comment by Lutra-Fs** [comment]
Ref: https://github.com/gjwgit/rattleng/issues/550
Currently on my device, multiple unrelated integration tests are failing.

**Comment by gjwgit** [comment]
Testing through the makefile is a little problematic on Windows - not developed/tested yet.

Tests are mostly working okay on Linux.

macOS on M1 is having issues with testing (and async issues) though older Mac is okay.

Thanks for the updates - I'll review shortly.

**Comment by gjwgit** [comment]
> Also I think it would be better to turn https://github.com/gjwgit/rattleng/blob/dev/lib/main.dart#L66 `alwaysOnTop` off to avoid the annoying pop up for integration test. I have read the comment but still don't get the idea why we force the app on top of the beginning.

I'll review this again - perhaps create an issue for this. It's a good point re the testing getting focus all the time because of this. An end user's expectation is that on starting the app it should be visible. I found that on starting the app it often ended up behind other windows on Linux.

**Review by gjwgit — COMMENTED** [review]
Thanks for the update.

- [x] I prefer and it is more standard to tap the SAVE icon to go directly to the filename chooser with SVG as the default, but allowable extensions are svg, pdf, and png, and so avoiding the SVG/PDF/PNG popup menu choice. 

- [x] If I change the filename extension to png then you should notice the filename extension and do the appropriate save.

- [x] If the extension is not recognized, then popup an error. 

- [ ] Retain the default filename.

This also avoid accidentally providing a .png name when I have selected SVG and thereby getting an SVG file saved into a .png filename. 

This will avoid some user error scenarios.

**Review by gjwgit — COMMENTED** [review]
Seems to have lost the default filename. 

On dev:

image


Now:

image

**Review by gjwgit — APPROVED** [review]
Thanks for the update. Looks good. Tested. Works well.

**Pull request merged**
