### PR TITLE
zy/338 TESTING: Demo model tree

### LINKED ISSUE #338: TESTING: Demo model tree
Use the CLUSTER test as a pattern for TREE test.

### PR DESCRIPTION
**Pull request by zheyxu**
# Pull Request Details

## What issue does this PR address

- TESTING: Demo model tree

- Link to associated issue: #338 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

**Review by gjwgit — APPROVED** [review]

**Review by gjwgit — CHANGES_REQUESTED** [review]
I think this is for DEMO yet you say LARGE?

**Comment by gjwgit** [comment]
Also, let's be consistent in the titles for the group and individual tests. Something like the dev `explore_missing_demo_test.dart` etc. Thanks.

**Comment by zheyxu** [comment]
Hi @gjwgit, updated.

**Review by gjwgit — CHANGES_REQUESTED** [review]
Not quite what I meant.

However, I am noticing the testing is really only testing the text labels the GUI is putting there, not that a tree has been built properly and as expected. Am I missing something? How is this considered to be testing? I expect the test to build the tree and check that the tree is correct in some sense.  The aim is to figure out if something has gone wrong when we make changes to the program and simply testing the titles won't do that.

Also, after you change parameters what do you expect the result on the tree to be - THAT is what needs to be tested, not just that the parameters are changed in the GUI!

I have also some format updates to push and request you follow the same style before the code can be merged.

Also, @junhaow1 has implemented common functionality that is to go into `integration_test/utils/XXXXX.dart`. Perhaps review and utilise here or do so through a separate PR. We are starting to see a lot of repeated code that we should not be seeing and this seems like a good approach.

Thanks,

**Comment by zheyxu** [comment]
Hi @gjwgit, the app itself has bugs. 
Tree model has issues from time to time.
Screenshot 2024-08-31 at 6 00 30 PM

**Comment by gjwgit** [comment]
Please capture these bugs and include them in test scripts so they are noticed.

**Review by gjwgit — APPROVED** [review]

**Pull request merged**
