### PR TITLE
Yyx/656 settings tuning validation

### PR DESCRIPTION
**Pull request by yixiangyin**
# Pull Request Details

## What issue does this PR address

- add settings: validate rather than tune

- Link to associated issue: #656 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [ ] Changes adhere to the style and coding guideline
- [ ] No confidential information
- [ ] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [ ] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [x] Tested on device:
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

**Review by gjwgit — CHANGES_REQUESTED** [review]
If the RESET button is tapped in the PARTTION part of the SETTINGS then the toggle should reset to the default value.

**Review by gjwgit — CHANGES_REQUESTED** [review]
The RESET happens when I click on the RESET button for DATASET TOGGLES. The RESET is meant to happen when I tap the PARTITION section's RESET button. Each of the RESET buttons relate to just that section.

**Comment by gjwgit** [comment]
> The RESET happens when I click on the RESET button for DATASET TOGGLES. The RESET is meant to happen when I tap the PARTITION section's RESET button. Each of the RESET buttons relate to just that section.

Fixed.

**Comment by yixiangyin** [comment]
> The RESET happens when I click on the RESET button for DATASET TOGGLES. The RESET is meant to happen when I tap the PARTITION section's RESET button. Each of the RESET buttons relate to just that section.

Ah I see. Thank you!

**Pull request merged**
