### PR TITLE
Zy/248 dataset reset page

### LINKED ISSUE #248: DATASET: On a RESET the page navigator is confused
load demo, go to the third page. reset, load demo, couldn't go to the next page. but could go to the previous page. seems the dots are not reset and the page number are not reset.

### PR DESCRIPTION
**Pull request by zheyxu**
# Pull Request Details

## What issue does this PR address

- DATASET: On a RESET the page navigator is confused

- Link to associated issue: #248 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [ ] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: [HERE]
- [x] Tested on at least one device
  - [ ] Android Phone
  - [ ] Android Emulator
  - [ ] Chrome on Android
  - [ ] Chrome
  - [ ] iOS
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added a reviewer

## Finalising

Once PR discussion is complete and reviewer has approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

**Review by gjwgit — CHANGES_REQUESTED** [review]
Please add a test for this as part of the PR

Load DEMO, navigate to page 3, RESET, Load DEMO navigate to page 2 then page 3 to confirm content.

Load DEMO, navigate to page 3, RESET, Load FILENAME (large dataset), navigate to page 2 and page 3 to confirm contents

**Comment by zheyxu** [comment]
Hi @gjwgit, tests added.

**Review by gjwgit — CHANGES_REQUESTED** [review]
Please note: **The point of a test is to test that the code works** - your test clearly shows that after loading the large dataset the test actually fails because there is an error message that indicates the the object ds was not found - the actual functionality of the app needs testing, not that the GUI can go from one page to another. So I am being mislead into thinking that it all worked when it actually fails! This is not useful testing.

**Comment by gjwgit** [comment]
This should probably entail a failure or a separate test to catch this failure and relate it to a separate issue. Then this issue IS focused just on the navigation problem.

**Comment by gjwgit** [comment]
In testing: DEMO, page 3, RESET, DEMO, page 3, is okay now.

But

DEMO, page 3, RESET, FILENAME large results in the forward arrow not working.

image

**Comment by zheyxu** [comment]
> In testing: DEMO, page 3, RESET, DEMO, page 3, is okay now.
> 
> But
> 
> DEMO, page 3, RESET, FILENAME large results in the forward arrow not working.
> 
> image

Fixed.

**Review by gjwgit — APPROVED** [review]
Tested on Linux. Navigation is working.

**Pull request merged**
